# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 07:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('lock', models.BooleanField(default=False)),
                ('mobile', models.CharField(max_length=13)),
                ('address', models.TextField(blank=True, null=True)),
                ('achievements', models.CharField(max_length=7)),
                ('position', models.CharField(blank=True, choices=[('', ''), ('President', 'President'), ('Vice President Education', 'Vice President Education'), ('Vice President Membership', 'Vice President Membership'), ('Vice President Public Relations', 'Vice President Public Relations'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Sergeant at Arms', 'Sergeant at Arms')], default='', max_length=31)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
