# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-03 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('lock', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('Evaluator', 'Evaluator'), ('TMOD', 'TMOD'), ('GE', 'GE'), ('TTM', 'TTM'), ('Timer', 'Timer'), ('Ah-Counter', 'Ah-Counter'), ('Grammarian', 'Grammarian'), ('Parliamentarian', 'Parliamentarian')], max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('lock', models.BooleanField(default=False)),
                ('topic', models.CharField(max_length=30)),
                ('number', models.PositiveSmallIntegerField()),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.UserData')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='club_name',
            field=models.CharField(default='GTMC', max_length=30),
        ),
        migrations.AddField(
            model_name='meeting',
            name='home_club',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speech',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Meeting'),
        ),
        migrations.AddField(
            model_name='speech',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.UserData'),
        ),
        migrations.AddField(
            model_name='role',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Meeting'),
        ),
        migrations.AddField(
            model_name='role',
            name='role_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.UserData'),
        ),
    ]
