# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-03 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180203_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('lock', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Best Speaker', 'Best Speaker'), ('Best Evaluator', 'Best Evaluator'), ('Best Role Player', 'Best Role Player'), ('Best Supplementary Role Player', 'Best Supplementary Role Player')], max_length=30)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Meeting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='speech',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
